### ISSUE TITLE
NC76 Meter doesn't move

### ISSUE THREAD

**Issue by MathieuCGit** [TukanStudios/TUKAN_STUDIOS_PLUGINS#1]
Hello,

First of all thanks a lot to all the hard work you put into those plugins, they are awesome ! However, I got in trouble with the fact Meters don't move. The sound change while I'm tweaking parameters but can't get the meters to reflect the changes.

Here is a gif to illustrate : [https://imgur.com/a/h85dq7M](https://imgur.com/a/h85dq7M)

I'm using the last version I have isntalled from reapack : [https://imgur.com/a/qQKrRpO](https://imgur.com/a/qQKrRpO)

**Comment by TukanStudios** [comment]
Hi and thank you for your mail. :)

For the VU meter: you can scale the 0dB down to -24dBFS as it is written on the right side of the plugin.
The NC76 just didn't make gain reduction, so the needle won't show gain reduction. 
For more gain reduction raise the input level. (big knob on the left)

Hope it helps, Tukan

**Comment by MathieuCGit** [comment]
Hello John,

Thanks for your reply, in fact the problem wasn't about gain reduction, the problem was related to the maj of the plugin. I remove every plugins and reinstall all and it's now perfectly working in the same session with the same paramters. If someone passing by has the same problem, it can be a solution.
